#!/bin/bash
set -e

SPECFILE=tail2kafka.spec

RPMNAM=$(grep "Name:"    $SPECFILE | awk '{print $2}')
RPMVER=$(grep "Version:" $SPECFILE | awk '{print $2}')
RPMREL=$(grep "Release:" $SPECFILE | awk '{print $2}')

TMPDIR=/tmp/$RPMNAM-$RPMVER
rm -rf $TMPDIR && mkdir $TMPDIR && mkdir $TMPDIR/.deps

cp Makefile src $TMPDIR -a
cp .deps/*.a $TMPDIR/.deps

RPMROOT=/usr/src/redhat
test -d $RPMROOT || RPMROOT="/root/rpmbuild"
mkdir -p $RPMROOT/SOURCES/

cd /tmp
tar czf $RPMNAM-$RPMVER.tar.gz $RPMNAM-$RPMVER
mv -f $RPMNAM-$RPMVER.tar.gz $RPMROOT/SOURCES/
cd -

OSARCH=$(uname -r | grep -o 'el.*')
OS=$(echo $OSARCH | cut -d'.' -f1)
ARCH=$(echo $OSARCH | cut -d'.' -f2)
test "$ARCH" != "" || ARCH="x86_64"

rpmbuild -bb $SPECFILE
mv $RPMROOT/RPMS/$ARCH/$RPMNAM-$RPMVER-$RPMREL.$ARCH.rpm $RPMNAM-$RPMVER-$RPMREL.$OS.$ARCH.rpm
mv $RPMROOT/RPMS/$ARCH/$RPMNAM-debuginfo-$RPMVER-$RPMREL.$ARCH.rpm $RPMNAM-debuginfo-$RPMVER-$RPMREL.$OS.$ARCH.rpm
